global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fraud_detection_api"
    static_configs:
      - targets: ["host.docker.internal:8000"]
# docker run -p 9090:9090 -v $(pwd)/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
# docker run -p 3000:3000 grafana/grafana
