apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fraud-detection-api
  template:
    metadata:
      labels:
        app: fraud-detection-api
    spec:
      containers:
      - name: fraud-detection-api
        image: fraud-detection-api:latest
        ports:
        - containerPort: 5000
      - name: server
        image: nginx
        ports:
        - containerPort: 80

# kubectl apply -f app-deployment.yaml
# kubectl get deployments