apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 5000
      nodePort: 5000

# kubectl apply -f app-service.yaml